# Name of your site (displayed in the header)
name: MatsieFTW!

# Short bio or description (displayed in the header)
description: Frontend Software Engiqueer in Portland, OR

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: /images/small-logo.jpg

footer-links:
  email: hi@matsie.net
  github: matsieftw
  linkedin: https://linkedin.com/in/mattiekenny
  rss: rss feed # just type anything here for a working RSS icon
  twitter: matsie

google_analytics: UA-2197930-13
url: https://matsie.net
baseurl: ""
permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
